- id: doi:10.1038/s41467-022-30925-0
  date: 2022-6-7
  tags:
    - network analysis

- id: doi:10.1093/bioinformatics/btz306
  date: 2021-12-15
  tags:
    - time-series analysis
    - miRNA-mRNA target prediction
